version: "3.8"
services:
  nginx:
    image: 'hosseindockerhub/speech_to_text_nginx:latest'
    container_name: nginx
    ports:
      - '80:80'
    networks:
      - app-proxy
  app:
    image: 'hosseindockerhub/speech_to_text:latest'
    ports:
      - '8080:8080'
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
    networks:
      - app-proxy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
networks:
  app-proxy:
