version: "3.8"
services:
  nginx:
    image: 'hosseindockerhub/speech_to_text_nginx:latest'
    container_name: nginx
    ports:
      - '80:80'
    networks:
      - app-proxy
  app:
    image: 'hosseindockerhub/speech_to_text:latest'
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
    networks:
      - app-proxy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:80/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
volumes:
  db-data:
networks:
  app-db:
  app-ui:
  app-proxy:
